### PR TITLE
Fix height/width of bullet in carousel

### LINKED ISSUE #192: [Accessibility] Bullets height/width fix in carousel
Currently in customer's website we see height/width of bullets as 12px and due to this we get a low score on SEO reason being for mobile "Tap targets are not sized appropriately", i.e interactive elements like buttons and links should be large enough (48x48px), or have enough space around them, to be easy enough to tap.

So change this from 12px to 15px to get over this SEO fix.

### PR DESCRIPTION
**Pull request by ujjwal5**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #192 

Test URLs:
- Before: https://main--fonterra-fernleaf--hlxsites.hlx.page/
- After: https://192-fix-bullet-seo--fonterra-fernleaf--hlxsites.hlx.page/en/products/formulated-milk-powder-for-children

### CODE REVIEW

**Review by sselvara — APPROVED** [review]

File: blocks/carousel/carousel.js [hunk 1]
```diff
@@ -179,7 +179,7 @@ function autoScrollCarousel() {
 }
 
 export default async function decorate(block) {
-  category = block.innerText;
+  category = block.innerText.replace(/\s/g, '');
```
Comment (ujjwal5) [inline blocks/carousel/carousel.js:182]: Removing all white spaces/tabs/new lines from carousel block innerText so that it can be added independently in the document like below:



carousel
--
recipe
