### PR TITLE
110 carousel accessibility fixes

### LINKED ISSUE #110: [Accessibility] Carousal
Report: https://pagespeed.web.dev/analysis/https-main--fonterra-fernleaf--hlxsites-hlx-live-en-products-milk-powder-for-whole-family/gak9bx7905?form_factor=mobile
Page: https://main--fonterra-fernleaf--hlxsites.hlx.live/en/products/milk-powder-for-whole-family

- [ ] "Explore our Product" wrong heading is used
image

- [ ] Background & foreground color
image

- [ ] Button name
image

- [ ] Serve images that are appropriately-sized
Note: We are using 1200px size image in url, which can be reduced to 400px
e.g https://main--fonterra-fernleaf--hlxsites.hlx.live/en/products/media_10849179472d8fb1243116089532bcd0d482421a8.png?width=350&format=pjpg&optimize=medium
image

- [x] Images don't have height/width
image

### PR DESCRIPTION
**Pull request by ujjwal5**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #110 

Test URLs:
- Before: https://main--fonterra-fernleaf--hlxsites.hlx.page/
- After: https://110-carousel-accessibility-fixes--fonterra-fernleaf--hlxsites.hlx.page/en/products/milk-powder-for-whole-family

### CODE REVIEW

File: blocks/buy-options/buy-options.js [hunk 1]
```diff
@@ -2,8 +2,10 @@ import {
   fetchPlaceholders,
 } from '../../scripts/lib-franklin.js';
 
+import { adjustImageSize } from '../../scripts/scripts.js';
+
 const getHTML = (row) => `<a target="_blank" href="${row.link}" title="${row.brand}" aria-label="${row.brand}">
-                <img alt="${row.brand}" src="${row.img}" width="100" height="42">
+                <img alt="${row.brand}" src="${adjustImageSize(row.img, 250)}" width="100" height="42">
```
Comment (mkbansal1) [inline blocks/buy-options/buy-options.js:8]: @ujjwal5  For buy options, set the image size to 100

**Review by mkbansal1 — CHANGES_REQUESTED** [review]

File: blocks/buy-options/buy-options.js (hunk 1 above)
Comment (mkbansal1) [inline blocks/buy-options/buy-options.js:8]: Wrong urls are generated 
https://110-carousel-accessibility-fixes--fonterra-fernleaf--hlxsites.hlx.pagehttps//main--fonterra-fernleaf--hlxsites.hlx.live/images/media_1faaf2f58aa1801b72aac44238ff67d8198b73cf5.png?width=250

**Review by mkbansal1 — CHANGES_REQUESTED** [review]

File: blocks/buy-options/buy-options.js (hunk 1 above)
Comment (ujjwal5) [reply blocks/buy-options/buy-options.js:8]: yes, I'm working on this..

**Review by mkbansal1 — APPROVED** [review]
